version: '3.3'

services:

   jenkins:
     image: jenkins/jenkins:latest
     ports:
       - "8080:8080"
     volumes:
       - ./data-jenkins:/var/jenkins_home
     restart: always
     
   artifactory:
     image: docker.bintray.io/jfrog/artifactory-oss:latest
     ports:
       - "8081:8081"
       - "8082:8082"
     volumes:
       - ./data-artifactory:/var/opt/jfrog/artifactory
     restart: always
     
   sonarqube:
     image: sonarqube:latest
     ports:
       - "9000:9000"
     volumes:
       - ./data-sonarqube/extensions:/opt/sonarqube/extensions
       - ./data-sonarqube/logs:/opt/sonarqube/logs
       - ./data-sonarqube/conf:/opt/sonarqube/conf
       - ./data-sonarqube/data:/opt/sonarqube/data
     restart: always
     
   gitlab:
     image: gitlab/gitlab-ee:latest
     ports:
       - "443:443"
       - "80:80"
       - "2222:22"
     volumes:
       - ./data-gitlab/config:/etc/gitlab
       - ./data-gitlab/logs:/var/log/gitlab
       - ./data-gitlab/data:/var/opt/gitlab
     restart: always
       
